# Guessing Game
This is a simple "guess the number" game built with JavaScript.

## How to Play
- To play the game, simply enter a number between 1 and 10 in the input field and click the "Submit Guess" button. 
- You will be told if your guess is too high or too low, and you can continue guessing until you correctly guess the number. 
- The game keeps track of the number of guesses you make, so you can try to beat your previous score.

## Customization
If you'd like to customize the game, you can adjust the range of the random number generated by changing the 10 value in the Math.random() * 10 expression to a different number. You can also modify the styling of the game to suit your preferences.
